language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt > /dev/null # discard installation output
  - pip install .
  - pip install --upgrade pytest-cov pytest
  - pip install codecov
script:
  - ls -R
  - pytest tests/test_function_basis.py
  - pytest tests/test_ode.py
  - pytest tests/test_pde.py
  - pytest tests/test_pde_spherical.py
  - pytest tests/test_temporal.py
# after_success:
  # - codecov
